### PR TITLE
Add `schedule` Command and Format Fixes

### LINKED ISSUE #63: Create Add Delivery Command to Person

### LINKED ISSUE #74: Change Format for DeliveryDay to Number
We would preferably want to change it to using numbers instead (e.g. 1 = Mon, 2 = Tue) in the future. This involves using `DateTimeFormatter.ofPattern("u");`.

_Originally posted by @DenseLance-alt in https://github.com/AY2526S2-CS2103T-W14-2/tp/pull/72#discussion_r2902770574_

### LINKED ISSUE #96: Edit Javadoc for in Person and Delivery class
# Change to be made
* Clarify the second constructor to only be used when `delivery != null`.
* Remove the word "recurring" in the `Delivery` class.

### PR DESCRIPTION
**Pull request by BenedTj**
Closes #63.
Closes #74.
Closes #96.

# Notable Changes
1. Move `AddCommandParser#arePrefixesPresent` into the `ParserUtil` class as a public parsing utility method.
2. Add `NUMBER_FORMATTER` and `convertDayNumberToDayWord` method in `DeliveryDay` class.
3. Add `TODO`s for methods or code snippets that need to be modified after planned refactoring of `DeliveryDay`.
4. Add `NumberOfDays` under the package `seedu.address.model.delivery.fields` to accommodate `schedule` command field `/n` that is not an attribute of the `Delivery` model.
5. Develop `DeliveryUtil` and delivery field parsing utility methods in the `ParserUtil` class.
6. Add parsing for `schedule` command.
7. Update tests for the new classes and functionalities added.

### CODE REVIEW

**Review by elijah-ng — COMMENTED** [review]
Some nits on comments and use of constants.

File: src/main/java/seedu/address/model/delivery/fields/NumberOfDays.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+     * Returns true if a given string is a valid
+     * positive number of days.
+     */
+    public static boolean isValidNumberOfDays(String test) {
+        if (test == null) {
+            throw new NullPointerException();
+        }
+
+        try {
+            int number = Integer.parseUnsignedInt(test);
```
Comment (Chen-Beitian) [inline src/main/java/seedu/address/model/delivery/fields/NumberOfDays.java]: Using `int` is sufficient for the domain, and better reflects the expected range of values for "number of days".
You may consider using `Integer.parseInt(test)`.

Comment (BenedTj) [reply src/main/java/seedu/address/model/delivery/fields/NumberOfDays.java]: Thank you for your comment @Chen-Beitian! To give some context to why I chose to use `Integer.parseUnsignedInt` here, I used `Integer.parseUnsignedInt` because "number of days" can only take non-negative values and it is the way that the method detects invalid "number of days" values that are negative since attempting to invoke `Integer.parseUnsignedInt` on a negative value would throw a `NumberFormatException`, which is interpreted as the value being invalid. Furthermore, since the Java does not have a type that wraps unsigned integers, I have used `int` in this case. What do you think about this?

File: src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+                           new ScheduleCommand(INDEX_FIRST_PERSON, delivery));
+    }
+
+    @Test
+    public void parse_repeatedCompulsoryField_failure() {
+        String validExpectedDeliveryString = INDEX_FIRST_PERSON.getOneBased() + START_DATE_DESC_BOB
+                + NUMBER_OF_DAYS_DESC_BOB + TIME_DESC_BOB + DAYS_DESC_BOB;
+
+        // multiple start dates
+        assertParseFailure(parser, validExpectedDeliveryString + START_DATE_DESC_BOB,
```
[the remark this answers is not in the document]
Comment (BenedTj) [reply src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java]: Thank you @elijah-ng, I will resolve this conversation!
