### PR TITLE
Fix Error Message-Related Issues

### LINKED ISSUE #324: [PE-D][Tester B] Invalid date range message is logically incorrect
### Steps:

1. Run schedule 1 st/2026-05-10 ed/2026-05-01 tm/12:00 d/123.

Expected: Message should say start date must not be after end date.
Actual: Message says “must not be before”.

Image

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #327: [PE-D][Tester C] Error message for invalid date is incorrect
I wanted to test invalid dates like Feb 30/ Feb 31
testcase: find-delivery dt/2026-02-30
error message: Date is not valid. It should be in the format yyyy-MM-dd.

Image

Expected: Date is invalid

The current error message suggests that the date format I have entered is incorrect even though I did use the yyyy-MM-dd format. 
The error was due to the fact that Feb 30 is an invalid date so the error should be specific to that error (maybe: invalid date) instead of saying that date is invalid as it should follow the format of yyyy-MM-dd

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #332: [PE-D][Tester A] Error message when schedule start date is after end date is wrong
Image

It should be start date must not be after the end date

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #350: [PE-D][Tester E] Logical mistake in error message for Schedule/Reschedule command
The error message is incorrect as it should state that the start date should not be _after_ the end date, not _before_.

Image

This is a relatively minor issue but beyond a typo, it is a logical mistake. With the command being of a valid format and all other fields having valid values, the user would have to see past the mistake in the error message to be able to remedy it. Therefore, this could pose occasional inconveniences to the user when they make a mistake in typing the input for start and end dates in the `schedule` command, with all other input being valid.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #360: [PE-D][Tester D] Feature Flaw: Misleading error message for start and end date in schedule command
# Description
When entering a invalid start date (start date is after the end date) in the schedule command, the error message says:

Image

I think a valid start date should be before the end date.

# Potential problems
* Confuses the user on what is a valid start date is.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by BenedTj**
Closes #324.
Closes #327.
Closes #332.
Closes #350.
Closes #360.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -34,7 +34,8 @@
 public class ParserUtil {
 
     public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
-    public static final String MESSAGE_INVALID_DATE = "Date is not valid. It should be in the format yyyy-MM-dd.";
+    public static final String MESSAGE_INVALID_DATE =
+            "Date is not valid. It should be a real date and in the format yyyy-MM-dd";
```
Comment (DenseLance-alt) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Hi ben, for all of the issues regarding date parsing:

Image

Image


You will need to specify this case under known issues / coming soon of UG, no need to put it under planned enhancements of DG. Thanks!

**Review by DenseLance-alt — COMMENTED** [review]
Hi Ben, good work! Would just need to update the documentation based on my comments. Thanks!

**Comment by DenseLance-alt** [comment]
You would also need to tag the other duplicated bugs so that all of them will be fixed in one shot when closing this PR.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 1 above)
Comment (BenedTj) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: Hello @DenseLance-alt, I added a line in the "Known issues" section of the User Guide in [3d13a59](https://github.com/AY2526S2-CS2103T-W14-2/tp/pull/383/commits/3d13a5977993766013fc9a7bc8031ec39a7cb03e). Please do check that I have included all problems properly.

File: docs/UserGuide.md [hunk 2]
```diff
@@ -487,6 +487,7 @@ If you like to find customers matching any of the filters (e.g. find all custome
 
 1. **Application window opens off-screen**: If you used ServeMate on a second screen and later switched to using a single screen, the application window may open off-screen for future start-ups.
    <br>**Solution**: Delete the `preferences.json` file located in the same folder as `ServeMate.jar` before restarting ServeMate.
+2. **Error message regarding date parsing**: If you entered either a date string with an invalid format or an invalid date, ServeMate does not specify which issue the input has.
```
Comment (DenseLance-alt) [inline docs/UserGuide.md]: Hi Ben, I think you have placed this in the wrong position, since the warning box below this is referring to the first point (of modifying preferences.json).

Comment (DenseLance-alt) [reply docs/UserGuide.md]: In this section, you should also try to include a remedy. 

You should also provide examples for both cases too.

**Comment by DenseLance-alt** [comment]
Hi Ben, there are some nits to fix.

File: docs/UserGuide.md (hunk 2 above)
Comment (BenedTj) [reply docs/UserGuide.md]: Hello @DenseLance-alt, thank you for pointing it out! I have decided to move it to the "Coming Soon" section since I have found that this is more suitable.

File: docs/UserGuide.md [hunk 3]
```diff
@@ -512,3 +512,4 @@ Use the `find` command to search for the customer you want for faster navigation
 2. **Refresh delivery panel:** Currently, you need to relaunch ServeMate to view deliveries scheduled for the new day. Soon, you will be able to refresh the delivery panel whenever needed to view deliveries scheduled on the current day without relaunching ServeMate.
 3. **Support for special characters in a customer's name**: You will be able to enter names containing special characters (e.g. `s/o`), which may appear in your customer's legal name.
 4. **Support for alphabets, special characters and spaces in a customer's phone number**: You will be able to enter phone numbers containing alphabets, special characters and spaces. This allows you to specify country codes and multiple phone numbers for a customer (e.g. `+65 9876 5432 (HP) 6560-6060 (Office)`).
+5. **More specific error message regarding date parsing**: If you entered either a date string with an invalid format (e.g. `02026-12-03`) or an invalid date (`2026-02-29`), ServeMate will specify which of either cases caused the date string to be invalid. This allows you to immediately be notified of the issue and rectify it.
```
Comment (DenseLance-alt) [inline docs/UserGuide.md]: You should try to explain why one is invalid format and the other is invalid date, similar to the CS2103T website, to prevent confusing readers.

Comment (BenedTj) [reply docs/UserGuide.md]: Thank you for the suggestion @DenseLance-alt! I have updated this in [7e2afb9](https://github.com/AY2526S2-CS2103T-W14-2/tp/pull/383/commits/7e2afb9c2c423191c59e856d0fd3092f00716e3a).

File: docs/UserGuide.md [hunk 4]
```diff
@@ -366,7 +366,7 @@ Format: `schedule INDEX st/START_DATE ed/END_DATE tm/DELIVERY_TIME d/DELIVERY_DA
 * The index refers to the index number shown in the displayed customer list.
 * The index **must be a positive integer** 1, 2, 3, …​
 * `DELIVERY_DAYS` must be a set of numbers **within the range of 1-7 inclusive** without whitespaces where 1 = Monday, 2 = Tuesday, …​, 7 = Sunday.
-* `24:00` is not a valid value for `DELIVERY_TIME`.
+* `24:00` is not a valid value for `DELIVERY_TIME` and `00:00` should be entered instead.
```
Comment (DenseLance-alt) [inline docs/UserGuide.md]: Wait a moment, would it be better if we say we restrict time from 00:00 to 23:59 instead?

E.g. Ensure that DELIVERY_TIME is in a 24-hour format between 00:00 and 23:59.

Put this in the notes right under Features heading, so that it can apply to all of our features.

File: docs/UserGuide.md [hunk 5]
```diff
@@ -519,3 +519,11 @@ Use the `find` command to search for the customer you want for faster navigation
 2. **Refresh delivery panel:** Currently, you need to relaunch ServeMate to view deliveries scheduled for the new day. Soon, you will be able to refresh the delivery panel whenever needed to view deliveries scheduled on the current day without relaunching ServeMate.
 3. **Support for special characters in a customer's name**: You will be able to enter names containing special characters (e.g. `s/o`), which may appear in your customer's legal name.
 4. **Support for alphabets, special characters and spaces in a customer's phone number**: You will be able to enter phone numbers containing alphabets, special characters and spaces. This allows you to specify country codes and multiple phone numbers for a customer (e.g. `+65 9876 5432 (HP) 6560-6060 (Office)`).
+5. **Increase specificity of error message for date parsing**: If you entered either a date string with an invalid format or an invalid date, ServeMate will specify which of either cases caused the date string to be invalid. This allows you to immediately be notified of the issue and rectify it.
```
Comment (DenseLance-alt) [inline docs/UserGuide.md:525]: This should include datetime parsing too.

**Review by DenseLance-alt — COMMENTED** [review]
Hi Ben, I have noted some pointers that might work!

File: docs/UserGuide.md (hunk 4 above)
Comment (BenedTj) [reply docs/UserGuide.md]: Good idea @DenseLance-alt! I have implemented it in [bfce510](https://github.com/AY2526S2-CS2103T-W14-2/tp/pull/383/commits/bfce5101218ea5b1ec7695bcccdbec0b8cd4d05b).

File: docs/UserGuide.md [hunk 6]
```diff
@@ -213,7 +213,8 @@ You can refer to the [Features](#features) section below to look up details abou
 * Dates are in `yyyy-MM-dd` format, where `yyyy` is the 4-digit year, `MM` is the 2-digit month, and `dd` is the 2-digit day.<br>
   e.g. 9th March 2026 can be written as `2026-03-09`.
 
-* Times should be in the 24-hour format and be between `00:00` and `23:59`.
+* Times should be in the 24-hour `HH:mm` format, where `HH` is the 2-git hour and `mm` is the 2-digit minute, and be between `00:00` and `23:59`.<br>
```
Comment (DenseLance-alt) [inline docs/UserGuide.md]: There is a spelling mistake for 2-digit as `2-git` hour.

Comment (BenedTj) [reply docs/UserGuide.md]: Thank you for pointing that out @DenseLance-alt, I have resolved it in [44e376a](https://github.com/AY2526S2-CS2103T-W14-2/tp/pull/383/commits/44e376a965b8e17ae283dce9da62db206eb6b597).

**Review by DenseLance-alt — APPROVED** [review]
LGTM 🚀 

Great work as always!
